sudo: false
language: bash
os:
  - linux
install:
  - shellcheck --version
  - go get -u mvdan.cc/sh/cmd/shfmt
script:
  - shellcheck $TRAVIS_BUILD_DIR/media_merge.sh
  - shfmt -i 2 -d -p -ci $TRAVIS_BUILD_DIR/media_merge.sh
